enum TickType {
    UNDEFINED, FIRSTTICK, NORMALTICK, LASTTICK;
}

enum ActivityType{
    UNDEFINED, ROOTACTIVITY, NODEACTIVITY, ENDPOINTACTIVITY, ENDPOINTDETAILACTIVITY;

}

enum TimeUnits{
    WEEKDAYS, WEEKENDS, EVERYDAY, FIRSTOFTHEMONTH;
}

enum PlanerStatus{
    NOTSTARTED, INPROGRESS, COMPLETED, MISSED,
    DOONFIRSTOCASION, HIGHIMPORTANCE, NORMALIMPORTANCE, LOWIMPORTANCE;
}